name: maily
description: Maily aims to become a fully featured email app once it has grown up.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+96

environment:
  flutter: ">=3.35.0"
  sdk: '>=3.9.0 <5.0.0'

dependencies:
  enough_mail_app:
    git:
      url: https://github.com/Enough-Software/enough_mail_app.git
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0-beta.4
  go_router: ^16.2.0
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.1.5

dependency_overrides:
  # collection: ^1.18.0
  # device_info_plus: ^9.1.0
  # package_info_plus: ^5.0.0
  # intl: ^0.19.0
  # http: ^1.2.1 # for dart_code_metrics
  # xml: ^6.5.0
  # ffi: ^2.1.0
  # uuid: ^4.0.0 # for dart_code_metrics
  # web: ^0.4.0 # for flutter test from SDK / http
  # pdfx: ^2.6.0
  # js: ^0.7.1 # for pdfx 2.6
  # webview_flutter_android: 3.16.1 # compare https://github.com/pichillilorenzo/flutter_inappwebview/issues/2150

  # out-comment the following to enable git-based development:
  # enough_mail:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail.git
  # enough_mail_app:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail_app.git
  # enough_mail_flutter:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail_flutter.git
  # enough_mail_html:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail_html.git
  # enough_media:
  #   git:
  #     url: https://github.com/Enough-Software/enough_media.git
  # enough_icalendar:
  #   git:
  #     url: https://github.com/Enough-Software/enough_icalendar.git
  # enough_mail_icalendar:
  #   git:
  #     url: https://github.com/Enough-Software/enough_mail_icalendar.git
  # enough_icalendar_export:
  #   git:
  #     url: https://github.com/Enough-Software/enough_icalendar_export.git
  # enough_html_editor:
  #   git:
  #     url: https://github.com/Enough-Software/enough_html_editor.git
  # enough_text_editor:
  #   git:
  #     url: https://github.com/Enough-Software/enough_text_editor.git
  # enough_ascii_art:
  #   git:
  #     url: https://github.com/Enough-Software/enough_ascii_art.git
  # enough_giphy_flutter:
  #   git:
  #     url: https://github.com/Enough-Software/enough_giphy_flutter.git
  # enough_platform_widgets:
  #   git:
  #     url: https://github.com/Enough-Software/enough_platform_widgets.git
  # out-comment the following to enable local development:
  # enough_mail:
  #   path: ../enough_mail
  # enough_mail_app:
  #   path: ../enough_mail_app
  # enough_mail_flutter:
  #   path: ../enough_mail_flutter
  # enough_mail_html:
  #   path: ../enough_mail_html
  # enough_icalendar:
  #   path: ../enough_icalendar
  # enough_mail_icalendar:
  #   path: ../enough_mail_icalendar
  # enough_giphy:
  #   path: ../enough_giphy
  # enough_giphy_flutter:
  #   path: ../enough_giphy_flutter
  # enough_icalendar_export:
  #   path: ../enough_icalendar_export
  # enough_media:
  #   path: ../enough_media
  # enough_html_editor:
  #   path: ../enough_html_editor
  # enough_text_editor:
  #   path: ../enough_text_editor
  # enough_ascii_art:
  #   path: ../enough_ascii_art
  # enough_platform_widgets:
  #   path: ../enough_platform_widgets
  
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.6
  custom_lint: ^0.6.2
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # For localization / l10n:
  generate: false

  assets:
    - assets/images/
   
    # - assets/images/
    # - assets/images/providers/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
